# Generated by Django 2.1 on 2019-10-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_dataset_no_of_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='no_of_keywords',
            new_name='volume',
        ),
    ]
